### ISSUE TITLE
golang x kubernetes 周りを調べる

### ISSUE THREAD

**Issue by sataga** [easy-to-study/go_study#10]
https://pkg.go.dev/k8s.io/client-go/kubernetes?tab=doc なんていうものがあるらしい。
ので、調べてみる。

- [x] Go勉強(1)　mac＋VSCode＋Go環境を設定 - Qiita
https://qiita.com/oruharo/items/545378eae5c707f717ed

シリーズ５まであるので一通り動かしつつ理解する

- [x] [client-goでKubernetesのAPIを試す](https://pizi.netlify.com/posts/kubernetes-client-go-example/)
- [x] [Go言語からkubernetes APIを呼び出すクライアント「client-go」の紹介 - Soon Lazy](http://ks888.hatenablog.com/entry/2017/12/25/001259)

↑を参考に基本的な使い方をやってみる

**Comment by sataga** [comment]
むむむ。とりあえず動かしてみようとしたらエラーが出てしまう。。
```
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes   master 
-> % go run main.go                                                                                                                                             23:37:15 - 23:39:33
build command-line-arguments: cannot load k8s.io/apimachinery/pkg/apis/meta/v1: module k8s.io/apimachinery/pkg/apis/meta: Get https://proxy.golang.org/k8s.io/apimachinery/pkg/apis/meta/@v/list: EOF
```

公式サンプルを動かしてみよう。
- [x] [client-go/examples/out-of-cluster-client-configuration at master · kubernetes/client-go](https://github.com/kubernetes/client-go/tree/master/examples/out-of-cluster-client-configuration)

エラーが止まらん
```
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master 
-> % go run main.go                                                                                                                                             23:56:47 - 23:58:02
build command-line-arguments: cannot load k8s.io/apimachinery/pkg/api/errors: module k8s.io/apimachinery/pkg/api/errors: Get https://proxy.golang.org/k8s.io/apimachinery/pkg/api/errors/@v/list: read tcp [::1]:54478->[::1]:1110: read: connection reset by peer
```

バージョンリストが取れてないっぽく見えたので公式から最新バージョン調べて当ててみた
- [x] [go.dev · go.dev](https://pkg.go.dev/)
```
<抜粋>
	"k8s.io/apimachinery/pkg/api/errors@v0.17.3"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1@v0.17.3"
	"k8s.io/client-go/kubernetes@v0.17.3"
	"k8s.io/client-go/tools/clientcmd@v0.17.3"
```
```
<結果>
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master 
-> % go run main.go                                                                                                                                             23:59:33 - 00:00:03
package main
        imports k8s.io/apimachinery/pkg/api/errors@v0.17.3: can only use path@version syntax with 'go get'
package main
        imports k8s.io/apimachinery/pkg/apis/meta/v1@v0.17.3: can only use path@version syntax with 'go get'
package main
        imports k8s.io/client-go/kubernetes@v0.17.3: can only use path@version syntax with 'go get'
package main
        imports k8s.io/client-go/tools/clientcmd@v0.17.3: can only use path@version syntax with 'go get'
```

エラーログでググってみると、Readme見なさいっていう結論になっている。
- [x] Can't install client-go: "go: cannot use path@version syntax in GOPATH mode" · Issue #681 · kubernetes/client-go
https://github.com/kubernetes/client-go/issues/681

素直にReadmeに従うことにしてみる
-> 気持ちはカジュアルユーザー
```
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master 
-> % go get k8s.io/client-go@master                                                                                                                             00:04:20 - 00:05:22
go: finding k8s.io/client-go master
go: finding k8s.io master
go get k8s.io/client-go@master: k8s.io/client-go@master: invalid version: Get https://proxy.golang.org/k8s.io/client-go/@v/master.info: EOF
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master 
```

あれ・・？
> This assumes you are using go modules with go 1.11+. If you get a message like cannot use path@version syntax in GOPATH mode, see the instructions for enabling go modules.

go1.13なので、デフォルトでmodule Onになっているはずなんだが、、従いますm

```
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master 
-> % go version                                                                                                                                                 00:00:04 - 00:04:20
go version go1.13.5 darwin/amd64
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master 
-> % export GO111MODULE=on                                                                                                                                      00:05:22 - 00:07:38
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master 
-> % go env | grep GO111                                                                                                                                        00:07:38 - 00:07:47
GO111MODULE="on"
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master 
-> %    
```

もう一回やってみる
go get 
->変わんない
```
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master 
-> % go get k8s.io/client-go@master                                                                                                                             00:07:48 - 00:08:26
go: finding k8s.io master
go: finding k8s.io/client-go master
go get k8s.io/client-go@master: k8s.io/client-go@master: invalid version: Get https://proxy.golang.org/k8s.io/client-go/@v/master.info: EOF
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master 
```
go run で強行
-> 変わんない
```
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master 
-> % go run main.go                                                                                                                                             00:09:24 - 00:09:36
build command-line-arguments: cannot load k8s.io/apimachinery/pkg/api/errors: module k8s.io/apimachinery/pkg/api/errors: Get https://proxy.golang.org/k8s.io/apimachinery/pkg/api/errors/@v/list: read tcp [::1]:53094->[::1]:1110: read: connection reset by peer
```

ん〜〜〜〜〜〜〜....再起動して出直すことにします。。

**Comment by sataga** [comment]
再起動したので、一旦go runをもう一度。
```
(⎈ |minikube:examples) t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master ● 
-> % go run main.go                                                                                                                                             00:14:13 - 00:14:18
go: finding golang.org/x/oauth2 latest
go: downloading golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
go: downloading golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
go: finding k8s.io/utils latest
go: finding golang.org/x/time latest
go: extracting golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
go: extracting golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
go: finding golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
go: finding golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
# k8s.io/client-go/rest
/Users/t-sataga/go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)
(⎈ |minikube:examples) t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master ● 
-> %    
```

おおお？？

**Comment by sataga** [comment]
そのエラーは下の記事で見かけたぞ
- [x] [Go勉強(2)　kubernetes client-goのexamplesをbuildする - Qiita](https://qiita.com/oruharo/items/261d065340845149b4ce)

masterをつけなさいとのこと（カジュアルユーザーなので）
> "k8s.io/client-go/kubernetes@master"

```
(⎈ |minikube:examples) t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master ● 
-> % go run main.go                                                                                                                                             00:14:57 - 00:17:33
package main
        imports k8s.io/client-go/kubernetes@master: can only use path@version syntax with 'go get'
(⎈ |minikube:examples) t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master ● 
-> % go get k8s.io/client-go@master                                                                                                                             00:17:34 - 00:17:55
go: finding k8s.io/client-go master
go: downloading k8s.io/client-go v0.0.0-20200229082506-bcb30edc8b38
go: extracting k8s.io/client-go v0.0.0-20200229082506-bcb30edc8b38
(⎈ |minikube:examples) t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master ● 
```

ソースの中で指定したら怒られたけど、go get であれば通った。
ちなみに、module設定は以下で、関係なさそうだった。
```
(⎈ |minikube:examples) t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master ● 
-> % go env | grep GO111                                                                                                                                        00:19:53 - 00:20:13
GO111MODULE=""
(⎈ |minikube:examples) t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master ● 
-> %                                                                                                                                                            00:20:14 -         

```

**Comment by sataga** [comment]
気を取り直して go run する
```
(⎈ |minikube:examples) t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master ● 
-> % go run main.go                                                                                                                                             00:18:15 - 00:19:49
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/google/gofuzz v1.1.0
go: downloading golang.org/x/crypto v0.0.0-20200220183623-bac4c82f6975
go: downloading sigs.k8s.io/yaml v1.2.0
go: extracting github.com/google/gofuzz v1.1.0
go: extracting sigs.k8s.io/yaml v1.2.0
go: extracting golang.org/x/crypto v0.0.0-20200220183623-bac4c82f6975
go: extracting github.com/gogo/protobuf v1.3.1
go: downloading golang.org/x/sys v0.0.0-20191022100944-742c48ecaeb7
go: extracting golang.org/x/sys v0.0.0-20191022100944-742c48ecaeb7
go: finding github.com/gogo/protobuf v1.3.1
go: finding github.com/google/gofuzz v1.1.0
go: finding golang.org/x/crypto v0.0.0-20200220183623-bac4c82f6975
go: finding golang.org/x/sys v0.0.0-20191022100944-742c48ecaeb7
go: finding sigs.k8s.io/yaml v1.2.0
package main
        imports k8s.io/client-go/kubernetes@master: can only use path@version syntax with 'go get'
```

きーーーー！

**Comment by sataga** [comment]
importのところで`@master`を残してしまっていた。
消して再実行。
```
(⎈ |minikube:examples) t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master ● 
-> % go run main.go                                                                                                                                             00:22:03 - 00:22:07
go: downloading github.com/googleapis/gnostic v0.1.0
go: extracting github.com/googleapis/gnostic v0.1.0
go: finding github.com/googleapis/gnostic v0.1.0
panic: Get https://192.168.64.3:8443/api/v1/pods: dial tcp 192.168.64.3:8443: i/o timeout

goroutine 1 [running]:
main.main()
        /Users/t-sataga/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample/main.go:66 +0x7f2
exit status 2
(⎈ |minikube:examples) t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/official-sample   master ● 
-> %                                                                                                                                             
```

処理内でのエラーが出た。つまりはインストールは無事に終えたようだ。

**Comment by sataga** [comment]
すぐ動きそうなサンプルで試してみる
```
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/node   master ● 
-> % go run main.go                                                                                                                                             00:26:00 - 00:26:22
# k8s.io/client-go/rest
/Users/t-sataga/go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)
```

ああああ〜〜〜〜違うのでタァ

**Comment by sataga** [comment]
カジュアルユーザーを卒業しないといけないらしい
![image](https://user-images.githubusercontent.com/24913906/75628518-2737d980-5c1d-11ea-933d-87386af55dee.png)

Kubernetes versionを合わせる

```
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/node   master ● 
-> % minikube start                                                                                                                                             00:32:19 - 00:32:56
🎉  minikube 1.7.3 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.7.3
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

🙄  minikube v1.6.2 on Darwin 10.14.6
✨  Selecting 'hyperkit' driver from existing profile (alternates: [virtualbox])
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing hyperkit VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
🚀  Launching Kubernetes ... 
🏄  Done! kubectl is now configured to use "minikube"
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/node   master ● 
-> % go get k8s.io/client-go@v0.17.0                                                                                                                            00:34:56 - 00:35:43
go: finding k8s.io/client-go v0.17.0
go: downloading k8s.io/client-go v0.17.0
go: extracting k8s.io/client-go v0.17.0
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/node   master ● 
-> %               
```

**Comment by sataga** [comment]
キター
```
 t-sataga@MBA  ~/go/src/github.com/easy-to-study/go_study/package/client-go/kubernetes/node   master ● 
-> % go run main.go                                                                                                                                             00:39:10 - 00:40:53
[0] minikube
```
